name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6


      - name: Install SDL3 dependencies
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y libsdl3-0 libsdl3-dev libsdl3-ttf-dev libsdl3-image-dev

      - name: Setup Nim
        uses: alaviss/setup-nim@0.1.1
        with:
          version: stable
          path: 'nim'

      - name: Nim version
        run: nim --version

      - name: Check src/sdl3.nim
        run: |
          nim c -r src/sdl3.nim

      - name: Check src/sdl3_ttf.nim
        run: |
          nim c -r src/sdl3_ttf.nim